FROM python:3.13-slim

# 指定工作目錄
WORKDIR /app
# 將本地的 requirements.txt 與 app.py 複製到容器的 /app/ 目錄中
COPY requirements.txt app.py /app/
# 安裝 requirements.txt 中指定的 Python 套件
RUN pip install -r requirements.txt
# 在容器啟動時執行 app.py
CMD ["python", "app.py"]